### ISSUE TITLE
Could not find files configuration

### ISSUE THREAD

**Issue by ch5rus** [catppuccin/windows-files#12]
![image](https://github.com/catppuccin/windows-files/assets/159018522/1e4a7e06-bcb6-42dd-bf12-ef0350a627fa)

**Comment by ch5rus** [comment]
For more context, i am on 2021 IoT LTSC

**Comment by ch5rus** [comment]
I tried it in Alacritty. Same error.

**Comment by lebensterben** [comment]
Because you need to install the [`Files` app](https://www.microsoft.com/store/productId/9NGHP3DX8HDX?ocid=pdpshare). (This is a proprietary software and **NOT** the file explorer.)

**Comment by goraprial** [comment]
I was having the same issue. They could add this requirement to the Readme

**Comment by ch5rus** [comment]
That would be useful, I’ll add a pull request when I’m home from school if
it doesn’t exist already

**Comment by slashtechno** [comment]
> Because you need to install the [`Files` app](https://www.microsoft.com/store/productId/9NGHP3DX8HDX?ocid=pdpshare). (This is a proprietary software and **NOT** the file explorer.)

It seems it's open source: [files-community/files](https://github.com/files-community/files/)

**Comment by sgoudham** [comment]
Hey :wave:,

As per our README template, we link to the application in the README header as shown below but I appreciate that this not be as explicit as it could be, especially for a repository named `catppuccin/windows-files`.

![image](https://github.com/user-attachments/assets/16e10d93-defc-4b1e-86ad-433aecd84dcf)

I've created a PR to list the download of the 3rd party application as the first step so it's more explicit. Hope that's okay!
