### ISSUE TITLE
A parameter cannot be found that matches parameter name 'AsHashtable'

### ISSUE THREAD

**Issue by BugsyH** [catppuccin/windows-files#13]
![image](https://github.com/catppuccin/windows-files/assets/165338213/4c90622f-738d-4d63-8a79-2d3c3a09af6b)

Sorry i have no idea what other info to give

**Comment by sim-liberti** [comment]
IDK if you still need this, but you have to install this using powershell 7 ([download it here](https://learn.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-windows?view=powershell-7.4#winget))

**Comment by sgoudham** [comment]
As mentioned on the README, you will need to use a newer version of Powershell in order to use the script.
