### ISSUE TITLE
How to remove

### ISSUE THREAD

**Issue by pdimu** [catppuccin/windows-files#14]
Hi! I installed the Catppuccin theme for Files, but i don't know how to remove it anymore. Any help, please?

**Comment by sgoudham** [comment]
Hey :wave:,

Depending on your method of installation, the files configuration file is in a different directory inside your `%LOCALAPPDATA%` directory:

https://github.com/catppuccin/windows-files/blob/67f695481e0f93ba503bfac6890ff862ee971fd4/install.ps1#L60-L75

For example, if you installed via the Microsoft Store, the configuration file will be inside `%LOCALAPPDATA%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState\settings\user_settings.json` (I believe you can also open the configuration file from within the app settings?)

You should be able to remove the Catppuccin colours from this file, the keys that we modify are shown below:

https://github.com/catppuccin/windows-files/blob/67f695481e0f93ba503bfac6890ff862ee971fd4/install.ps1#L51-L54

**Comment by pdimu** [comment]
Thank you!

**Comment by cardin** [comment]
I thought this information is actually pretty important - it should be included in the README as well.
