### ISSUE TITLE
solid base background

### ISSUE THREAD

**Issue by FractalGeodes** [catppuccin/windows-files#6]
Kind of disappointed that the main window isn't coloured (example image below, the icon uses a mocha background colour)
![image](https://user-images.githubusercontent.com/110815694/208245325-cb64f354-915f-4a9b-95e5-1b8940470aa2.png)

Is this a limitation at all or just an oversight? Or did we install wrong because that's possible too

**Comment by DakshG07** [comment]
Weird. Send a full screenshot, maybe? Want to see this in context.

**Comment by FractalGeodes** [comment]
![Files_1TO0J4lSU1](https://user-images.githubusercontent.com/110815694/208333797-c7096982-ad35-4b73-9f7e-42fc172630b3.gif)

Here's a gif, the settings window is coloured correctly but the main background isn't

**Comment by DakshG07** [comment]
That was intended, Files has an acrylic/mica-like effect. I should probably add an option for a solid base background. I’ll start working on this.
